// Code generated by protoc-gen-go.
// source: IM.Message.proto
// DO NOT EDIT!

/*
Package IM_Message is a generated protocol buffer package.

It is generated from these files:
	IM.Message.proto

It has these top-level messages:
	IMMsgData
	IMMsgDataAck
	IMMsgDataReadAck
	IMMsgDataReadNotify
	IMClientTimeReq
	IMClientTimeRsp
	IMUnreadMsgCntReq
	IMUnreadMsgCntRsp
	IMGetMsgListReq
	IMGetMsgListRsp
	IMGetLatestMsgIdReq
	IMGetLatestMsgIdRsp
	IMGetMsgByIdReq
	IMGetMsgByIdRsp
	IMGetLostMsgListReq
	IMGetLostMsgListRsp
	IMQuerySentMsgReq
	IMQuerySentMsgRsp
*/
package IM_Message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "IM/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// service id  0x0003
type IMMsgData struct {
	// cmd id:		0x0301
	FromUserId       *uint32                `protobuf:"varint,1,req,name=from_user_id" json:"from_user_id,omitempty"`
	ToSessionId      *uint32                `protobuf:"varint,2,req,name=to_session_id" json:"to_session_id,omitempty"`
	MsgId            *uint32                `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	CreateTime       *uint32                `protobuf:"varint,4,req,name=create_time" json:"create_time,omitempty"`
	MsgType          *IM_BaseDefine.MsgType `protobuf:"varint,5,req,name=msg_type,enum=IM.BaseDefine.MsgType" json:"msg_type,omitempty"`
	MsgData          []byte                 `protobuf:"bytes,6,req,name=msg_data" json:"msg_data,omitempty"`
	AttachData       []byte                 `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *IMMsgData) Reset()                    { *m = IMMsgData{} }
func (m *IMMsgData) String() string            { return proto.CompactTextString(m) }
func (*IMMsgData) ProtoMessage()               {}
func (*IMMsgData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMMsgData) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMMsgData) GetToSessionId() uint32 {
	if m != nil && m.ToSessionId != nil {
		return *m.ToSessionId
	}
	return 0
}

func (m *IMMsgData) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgData) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *IMMsgData) GetMsgType() IM_BaseDefine.MsgType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return IM_BaseDefine.MsgType_MSG_TYPE_SINGLE_TEXT
}

func (m *IMMsgData) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *IMMsgData) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMMsgDataAck struct {
	// cmd id:		0x0302
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataAck) Reset()                    { *m = IMMsgDataAck{} }
func (m *IMMsgDataAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataAck) ProtoMessage()               {}
func (*IMMsgDataAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMMsgDataAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMMsgDataReadAck struct {
	// cmd id:		0x0303
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadAck) Reset()                    { *m = IMMsgDataReadAck{} }
func (m *IMMsgDataReadAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadAck) ProtoMessage()               {}
func (*IMMsgDataReadAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMMsgDataReadAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMMsgDataReadNotify struct {
	// cmd id:		0x0304
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadNotify) Reset()                    { *m = IMMsgDataReadNotify{} }
func (m *IMMsgDataReadNotify) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadNotify) ProtoMessage()               {}
func (*IMMsgDataReadNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMMsgDataReadNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMClientTimeReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMClientTimeReq) Reset()                    { *m = IMClientTimeReq{} }
func (m *IMClientTimeReq) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeReq) ProtoMessage()               {}
func (*IMClientTimeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type IMClientTimeRsp struct {
	// cmd id:		0x0306
	ServerTime       *uint32 `protobuf:"varint,1,req,name=server_time" json:"server_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMClientTimeRsp) Reset()                    { *m = IMClientTimeRsp{} }
func (m *IMClientTimeRsp) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeRsp) ProtoMessage()               {}
func (*IMClientTimeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMClientTimeRsp) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

type IMUnreadMsgCntReq struct {
	// cmd id:		0x0307
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMUnreadMsgCntReq) Reset()                    { *m = IMUnreadMsgCntReq{} }
func (m *IMUnreadMsgCntReq) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntReq) ProtoMessage()               {}
func (*IMUnreadMsgCntReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMUnreadMsgCntReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUnreadMsgCntRsp struct {
	// cmd id:		0x0308
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	TotalCnt         *uint32                     `protobuf:"varint,2,req,name=total_cnt" json:"total_cnt,omitempty"`
	UnreadinfoList   []*IM_BaseDefine.UnreadInfo `protobuf:"bytes,3,rep,name=unreadinfo_list" json:"unreadinfo_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMUnreadMsgCntRsp) Reset()                    { *m = IMUnreadMsgCntRsp{} }
func (m *IMUnreadMsgCntRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntRsp) ProtoMessage()               {}
func (*IMUnreadMsgCntRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMUnreadMsgCntRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetTotalCnt() uint32 {
	if m != nil && m.TotalCnt != nil {
		return *m.TotalCnt
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetUnreadinfoList() []*IM_BaseDefine.UnreadInfo {
	if m != nil {
		return m.UnreadinfoList
	}
	return nil
}

func (m *IMUnreadMsgCntRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgListReq struct {
	// cmd id:		0x0309
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin" json:"msg_id_begin,omitempty"`
	MsgCnt           *uint32                    `protobuf:"varint,5,req,name=msg_cnt" json:"msg_cnt,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListReq) Reset()                    { *m = IMGetMsgListReq{} }
func (m *IMGetMsgListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListReq) ProtoMessage()               {}
func (*IMGetMsgListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMGetMsgListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgCnt() uint32 {
	if m != nil && m.MsgCnt != nil {
		return *m.MsgCnt
	}
	return 0
}

func (m *IMGetMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 对于群而言，如果消息数目返回的数值小于请求的cnt,则表示群的消息能拉取的到头了，更早的消息没有权限拉取。
// 如果msg_cnt 和 msg_id_begin计算得到的最早消息id与实际返回的最早消息id不一致，说明服务器消息有缺失，需要
// 客户端做一个缺失标记，避免下次再次拉取。
type IMGetMsgListRsp struct {
	// cmd id:		0x030a
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin" json:"msg_id_begin,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,5,rep,name=msg_list" json:"msg_list,omitempty"`
	LastReadMsgId    *uint32                    `protobuf:"varint,6,opt,name=last_read_msg_id" json:"last_read_msg_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListRsp) Reset()                    { *m = IMGetMsgListRsp{} }
func (m *IMGetMsgListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListRsp) ProtoMessage()               {}
func (*IMGetMsgListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMGetMsgListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgListRsp) GetLastReadMsgId() uint32 {
	if m != nil && m.LastReadMsgId != nil {
		return *m.LastReadMsgId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdReq struct {
	// cmd id: 		0x030b
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdReq) Reset()                    { *m = IMGetLatestMsgIdReq{} }
func (m *IMGetLatestMsgIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdReq) ProtoMessage()               {}
func (*IMGetLatestMsgIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMGetLatestMsgIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdRsp struct {
	// cmd id:		0x030c
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	LatestMsgId      *uint32                    `protobuf:"varint,4,req,name=latest_msg_id" json:"latest_msg_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdRsp) Reset()                    { *m = IMGetLatestMsgIdRsp{} }
func (m *IMGetLatestMsgIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdRsp) ProtoMessage()               {}
func (*IMGetLatestMsgIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMGetLatestMsgIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetLatestMsgId() uint32 {
	if m != nil && m.LatestMsgId != nil {
		return *m.LatestMsgId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdReq struct {
	// cmd id: 		0x030d
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgIdList        []uint32                   `protobuf:"varint,4,rep,name=msg_id_list" json:"msg_id_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdReq) Reset()                    { *m = IMGetMsgByIdReq{} }
func (m *IMGetMsgByIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdReq) ProtoMessage()               {}
func (*IMGetMsgByIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMGetMsgByIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetMsgIdList() []uint32 {
	if m != nil {
		return m.MsgIdList
	}
	return nil
}

func (m *IMGetMsgByIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdRsp struct {
	// cmd id:		0x030e
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id" json:"session_id,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,4,rep,name=msg_list" json:"msg_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdRsp) Reset()                    { *m = IMGetMsgByIdRsp{} }
func (m *IMGetMsgByIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdRsp) ProtoMessage()               {}
func (*IMGetMsgByIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMGetMsgByIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgByIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLostMsgListReq struct {
	// cmd id:       0x030f
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	MsgAckList       []*IM_BaseDefine.MsgAckType `protobuf:"bytes,2,rep,name=msg_ack_list" json:"msg_ack_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMGetLostMsgListReq) Reset()                    { *m = IMGetLostMsgListReq{} }
func (m *IMGetLostMsgListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetLostMsgListReq) ProtoMessage()               {}
func (*IMGetLostMsgListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMGetLostMsgListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLostMsgListReq) GetMsgAckList() []*IM_BaseDefine.MsgAckType {
	if m != nil {
		return m.MsgAckList
	}
	return nil
}

func (m *IMGetLostMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLostMsgListRsp struct {
	// cmd id:       0x0310
	UserId           *uint32                  `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo `protobuf:"bytes,2,rep,name=msg_list" json:"msg_list,omitempty"`
	AttachData       []byte                   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *IMGetLostMsgListRsp) Reset()                    { *m = IMGetLostMsgListRsp{} }
func (m *IMGetLostMsgListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetLostMsgListRsp) ProtoMessage()               {}
func (*IMGetLostMsgListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IMGetLostMsgListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLostMsgListRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetLostMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMQuerySentMsgReq struct {
	// cmd id:      0x0311
	MsgId            *uint32 `protobuf:"varint,1,req,name=msg_id" json:"msg_id,omitempty"`
	FromId           *uint32 `protobuf:"varint,2,req,name=from_id" json:"from_id,omitempty"`
	ToId             *uint32 `protobuf:"varint,3,req,name=to_id" json:"to_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMQuerySentMsgReq) Reset()                    { *m = IMQuerySentMsgReq{} }
func (m *IMQuerySentMsgReq) String() string            { return proto.CompactTextString(m) }
func (*IMQuerySentMsgReq) ProtoMessage()               {}
func (*IMQuerySentMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IMQuerySentMsgReq) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMQuerySentMsgReq) GetFromId() uint32 {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return 0
}

func (m *IMQuerySentMsgReq) GetToId() uint32 {
	if m != nil && m.ToId != nil {
		return *m.ToId
	}
	return 0
}

func (m *IMQuerySentMsgReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMQuerySentMsgRsp struct {
	// cmd id:      0x0312
	FromId           *uint32 `protobuf:"varint,1,req,name=from_id" json:"from_id,omitempty"`
	DupMsg           *bool   `protobuf:"varint,2,req,name=dupMsg" json:"dupMsg,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMQuerySentMsgRsp) Reset()                    { *m = IMQuerySentMsgRsp{} }
func (m *IMQuerySentMsgRsp) String() string            { return proto.CompactTextString(m) }
func (*IMQuerySentMsgRsp) ProtoMessage()               {}
func (*IMQuerySentMsgRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *IMQuerySentMsgRsp) GetFromId() uint32 {
	if m != nil && m.FromId != nil {
		return *m.FromId
	}
	return 0
}

func (m *IMQuerySentMsgRsp) GetDupMsg() bool {
	if m != nil && m.DupMsg != nil {
		return *m.DupMsg
	}
	return false
}

func (m *IMQuerySentMsgRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgData)(nil), "IM.Message.IMMsgData")
	proto.RegisterType((*IMMsgDataAck)(nil), "IM.Message.IMMsgDataAck")
	proto.RegisterType((*IMMsgDataReadAck)(nil), "IM.Message.IMMsgDataReadAck")
	proto.RegisterType((*IMMsgDataReadNotify)(nil), "IM.Message.IMMsgDataReadNotify")
	proto.RegisterType((*IMClientTimeReq)(nil), "IM.Message.IMClientTimeReq")
	proto.RegisterType((*IMClientTimeRsp)(nil), "IM.Message.IMClientTimeRsp")
	proto.RegisterType((*IMUnreadMsgCntReq)(nil), "IM.Message.IMUnreadMsgCntReq")
	proto.RegisterType((*IMUnreadMsgCntRsp)(nil), "IM.Message.IMUnreadMsgCntRsp")
	proto.RegisterType((*IMGetMsgListReq)(nil), "IM.Message.IMGetMsgListReq")
	proto.RegisterType((*IMGetMsgListRsp)(nil), "IM.Message.IMGetMsgListRsp")
	proto.RegisterType((*IMGetLatestMsgIdReq)(nil), "IM.Message.IMGetLatestMsgIdReq")
	proto.RegisterType((*IMGetLatestMsgIdRsp)(nil), "IM.Message.IMGetLatestMsgIdRsp")
	proto.RegisterType((*IMGetMsgByIdReq)(nil), "IM.Message.IMGetMsgByIdReq")
	proto.RegisterType((*IMGetMsgByIdRsp)(nil), "IM.Message.IMGetMsgByIdRsp")
	proto.RegisterType((*IMGetLostMsgListReq)(nil), "IM.Message.IMGetLostMsgListReq")
	proto.RegisterType((*IMGetLostMsgListRsp)(nil), "IM.Message.IMGetLostMsgListRsp")
	proto.RegisterType((*IMQuerySentMsgReq)(nil), "IM.Message.IMQuerySentMsgReq")
	proto.RegisterType((*IMQuerySentMsgRsp)(nil), "IM.Message.IMQuerySentMsgRsp")
}

func init() { proto.RegisterFile("IM.Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x96, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x86, 0x21, 0xd9, 0xce, 0x65, 0x62, 0xc7, 0x89, 0x93, 0x9c, 0xe3, 0xa6, 0x1b, 0xc1, 0x8b,
	0xc2, 0x2b, 0xb7, 0xc8, 0xae, 0xcb, 0x5c, 0x80, 0x54, 0x40, 0x58, 0xa0, 0x49, 0x0a, 0x74, 0x27,
	0x30, 0xf2, 0x48, 0x65, 0x23, 0x89, 0x8a, 0x48, 0x15, 0x10, 0xd0, 0x45, 0xfb, 0x0a, 0x5d, 0xf5,
	0x01, 0x0a, 0x74, 0xd7, 0xd7, 0xe9, 0xeb, 0x14, 0xa4, 0xa4, 0x5c, 0x64, 0x3a, 0x46, 0x17, 0xce,
	0x52, 0x03, 0x72, 0xe6, 0x9b, 0xff, 0xe7, 0x90, 0x82, 0x2d, 0x97, 0x4c, 0x08, 0x0a, 0x41, 0x43,
	0x9c, 0xa4, 0x19, 0x97, 0x7c, 0x00, 0x77, 0x91, 0xfd, 0x1d, 0x97, 0x4c, 0x8e, 0xa8, 0xc0, 0x13,
	0x0c, 0x58, 0x52, 0x2d, 0x18, 0xfd, 0xb6, 0x60, 0xdd, 0x25, 0x44, 0x84, 0x27, 0x54, 0xd2, 0xc1,
	0x2e, 0x74, 0x83, 0x8c, 0xc7, 0x5e, 0x2e, 0x30, 0xf3, 0xd8, 0x74, 0x68, 0x39, 0xf6, 0xb8, 0x37,
	0xd8, 0x83, 0x9e, 0xe4, 0x9e, 0x40, 0x21, 0x18, 0x4f, 0x54, 0xd8, 0xd6, 0xe1, 0x4d, 0x58, 0x89,
	0x45, 0xa8, 0xbe, 0x5b, 0xfa, 0x7b, 0x07, 0x36, 0xfc, 0x0c, 0xa9, 0x44, 0x4f, 0xb2, 0x18, 0x87,
	0x6d, 0x1d, 0x1c, 0xc3, 0x9a, 0x5a, 0x24, 0x8b, 0x14, 0x87, 0x1d, 0xc7, 0x1e, 0x6f, 0x1e, 0xfc,
	0x37, 0x79, 0xc8, 0x41, 0x44, 0x78, 0x59, 0xa4, 0x38, 0xd8, 0x2a, 0x57, 0x4e, 0xa9, 0xa4, 0xc3,
	0x15, 0xc7, 0x1e, 0x77, 0x55, 0x42, 0x2a, 0x25, 0xf5, 0x3f, 0x96, 0xc1, 0x5d, 0xc7, 0x1a, 0x77,
	0x47, 0x39, 0x74, 0x6f, 0x79, 0x0f, 0xfd, 0xeb, 0x41, 0x1f, 0x56, 0x1f, 0xd2, 0x0e, 0x00, 0x16,
	0xa2, 0xbe, 0x82, 0x6e, 0xbd, 0x46, 0x93, 0xb5, 0x35, 0xd9, 0x7e, 0x83, 0xec, 0xa2, 0x5c, 0xa2,
	0xe8, 0x46, 0x85, 0x12, 0xb7, 0x2a, 0x7b, 0x8e, 0x74, 0xfa, 0x84, 0xa5, 0xbf, 0xc0, 0xce, 0x83,
	0xd2, 0x6f, 0xb9, 0x64, 0x41, 0xf1, 0x54, 0xd5, 0xb7, 0xa1, 0xef, 0x92, 0xe3, 0x88, 0x61, 0x22,
	0x2f, 0x59, 0x8c, 0xe7, 0x78, 0x33, 0x7a, 0xd1, 0x08, 0x89, 0x54, 0x59, 0x25, 0x30, 0xfb, 0x8c,
	0x59, 0xe9, 0xbd, 0x06, 0x1a, 0xbd, 0x86, 0x6d, 0x97, 0xbc, 0x4f, 0x32, 0xa4, 0x53, 0x22, 0xc2,
	0xe3, 0x44, 0x9e, 0xe3, 0xcd, 0x2c, 0xb6, 0xd1, 0xe5, 0xaf, 0xd6, 0xcc, 0x5e, 0x91, 0xce, 0xee,
	0xdd, 0x86, 0x75, 0xc9, 0x25, 0x8d, 0x3c, 0x3f, 0x91, 0x55, 0xc7, 0x07, 0xd0, 0xcf, 0xf5, 0x36,
	0x96, 0x04, 0xdc, 0x8b, 0x98, 0x90, 0xc3, 0x96, 0xd3, 0x1a, 0x6f, 0x1c, 0x3c, 0x6b, 0x34, 0x59,
	0x26, 0x77, 0x93, 0x80, 0x9b, 0x11, 0x7e, 0x5a, 0xaa, 0xcd, 0x53, 0x94, 0x44, 0x84, 0x67, 0x4c,
	0x98, 0xe1, 0x9b, 0x7a, 0xda, 0x8b, 0xf4, 0x6c, 0xb8, 0x54, 0xba, 0xb2, 0x0b, 0xdd, 0xd2, 0x25,
	0xef, 0x0a, 0x43, 0x96, 0x54, 0xa3, 0xd3, 0x87, 0x55, 0x15, 0x55, 0xad, 0x75, 0xe6, 0x2b, 0xf5,
	0xa7, 0x89, 0x69, 0xd2, 0x69, 0x99, 0x98, 0xd5, 0x84, 0x6b, 0xa5, 0x3b, 0x5a, 0x69, 0xc3, 0x84,
	0x6b, 0x99, 0x87, 0xb0, 0x15, 0x51, 0x21, 0x3d, 0xa5, 0xbb, 0x57, 0x1d, 0xcb, 0x15, 0xc7, 0x9a,
	0xd7, 0xd9, 0x37, 0x4b, 0x1d, 0xfc, 0x53, 0x94, 0x67, 0x54, 0xa2, 0x50, 0xfd, 0xb9, 0xd3, 0x25,
	0x9a, 0x60, 0x64, 0xf8, 0x61, 0x62, 0x58, 0x9e, 0xc2, 0x7b, 0xd0, 0x8b, 0x74, 0xa1, 0x5a, 0x9e,
	0xf6, 0x7c, 0xb4, 0xef, 0xf7, 0x8c, 0x3f, 0x2a, 0x96, 0x2d, 0x4d, 0x65, 0xbc, 0x76, 0xb9, 0xed,
	0xb4, 0xe6, 0x41, 0xfd, 0x6a, 0x42, 0x2d, 0x4f, 0xab, 0xfb, 0xe7, 0xae, 0xfd, 0xe8, 0xb9, 0x33,
	0x92, 0x46, 0xb5, 0xb1, 0x5c, 0x3c, 0x3a, 0xe1, 0x2f, 0xcb, 0x43, 0x4f, 0xfd, 0xeb, 0xb2, 0x94,
	0x6d, 0xbc, 0x4c, 0x88, 0x08, 0x0f, 0xfd, 0x6b, 0xcd, 0x6a, 0xac, 0x86, 0x86, 0x6a, 0x26, 0x69,
	0xee, 0x37, 0x65, 0xff, 0x7b, 0x53, 0x1f, 0xd4, 0xad, 0xf9, 0x2e, 0xc7, 0xac, 0xb8, 0xc0, 0x44,
	0x15, 0x52, 0x2d, 0xdd, 0xbd, 0x01, 0x56, 0x7d, 0xaf, 0xe8, 0x47, 0xfe, 0xf6, 0x91, 0xe8, 0x41,
	0x47, 0xf2, 0x05, 0x83, 0xe0, 0xce, 0x64, 0x2e, 0xf1, 0xeb, 0x4c, 0x56, 0xfd, 0xdc, 0x4c, 0xf3,
	0x94, 0x88, 0x50, 0x67, 0x5e, 0x33, 0xa6, 0x3a, 0x7a, 0x0e, 0xff, 0xfb, 0x3c, 0x9e, 0xc4, 0x3c,
	0xcc, 0x3f, 0x31, 0x9c, 0x48, 0x59, 0xfe, 0x8a, 0x5c, 0xe5, 0xc1, 0x9b, 0xd6, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x51, 0x96, 0x3b, 0x6d, 0xc3, 0x08, 0x00, 0x00,
}
