// Code generated by protoc-gen-go.
// source: IM.Server.proto
// DO NOT EDIT!

/*
Package IM_Server is a generated protocol buffer package.

It is generated from these files:
	IM.Server.proto

It has these top-level messages:
	IMStopReceivePacket
	IMValidateReq
	IMValidateRsp
	IMGetDeviceTokenReq
	IMGetDeviceTokenRsp
	IMRoleSet
	IMOnlineUserInfo
	IMMsgServInfo
	IMUserStatusUpdate
	IMUserCntUpdate
	IMServerKickUser
	IMServerPCLoginStatusNotify
	IMPushToUserReq
	IMPushToUserRsp
	IMGroupGetShieldReq
	IMGroupGetShieldRsp
	IMFileTransferReq
	IMFileTransferRsp
	IMFileServerIPReq
	IMFileServerIPRsp
*/
package IM_Server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// db_proxy
type IMStopReceivePacket struct {
	// cmd id:   0x0702
	Result           *uint32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMStopReceivePacket) Reset()                    { *m = IMStopReceivePacket{} }
func (m *IMStopReceivePacket) String() string            { return proto.CompactTextString(m) }
func (*IMStopReceivePacket) ProtoMessage()               {}
func (*IMStopReceivePacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMStopReceivePacket) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// db_proxy
type IMValidateReq struct {
	// cmd id:	0x0703
	UserName         *string `protobuf:"bytes,1,req,name=user_name" json:"user_name,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMValidateReq) Reset()                    { *m = IMValidateReq{} }
func (m *IMValidateReq) String() string            { return proto.CompactTextString(m) }
func (*IMValidateReq) ProtoMessage()               {}
func (*IMValidateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMValidateReq) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *IMValidateReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *IMValidateReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// db_proxy
type IMValidateRsp struct {
	// cmd id:	0x0704
	UserName         *string                 `protobuf:"bytes,1,req,name=user_name" json:"user_name,omitempty"`
	ResultCode       *uint32                 `protobuf:"varint,2,req,name=result_code" json:"result_code,omitempty"`
	ResultString     *string                 `protobuf:"bytes,3,opt,name=result_string" json:"result_string,omitempty"`
	UserInfo         *IM_BaseDefine.UserInfo `protobuf:"bytes,4,opt,name=user_info" json:"user_info,omitempty"`
	AttachData       []byte                  `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *IMValidateRsp) Reset()                    { *m = IMValidateRsp{} }
func (m *IMValidateRsp) String() string            { return proto.CompactTextString(m) }
func (*IMValidateRsp) ProtoMessage()               {}
func (*IMValidateRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMValidateRsp) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *IMValidateRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMValidateRsp) GetResultString() string {
	if m != nil && m.ResultString != nil {
		return *m.ResultString
	}
	return ""
}

func (m *IMValidateRsp) GetUserInfo() *IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *IMValidateRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// db_proxy
type IMGetDeviceTokenReq struct {
	// cmd id:	0x0705
	UserId           []uint32 `protobuf:"varint,1,rep,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMGetDeviceTokenReq) Reset()                    { *m = IMGetDeviceTokenReq{} }
func (m *IMGetDeviceTokenReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetDeviceTokenReq) ProtoMessage()               {}
func (*IMGetDeviceTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMGetDeviceTokenReq) GetUserId() []uint32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *IMGetDeviceTokenReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// db_proxy
type IMGetDeviceTokenRsp struct {
	// cmd id:	0x0706
	UserTokenInfo    []*IM_BaseDefine.UserTokenInfo `protobuf:"bytes,1,rep,name=user_token_info" json:"user_token_info,omitempty"`
	AttachData       []byte                         `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *IMGetDeviceTokenRsp) Reset()                    { *m = IMGetDeviceTokenRsp{} }
func (m *IMGetDeviceTokenRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetDeviceTokenRsp) ProtoMessage()               {}
func (*IMGetDeviceTokenRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IMGetDeviceTokenRsp) GetUserTokenInfo() []*IM_BaseDefine.UserTokenInfo {
	if m != nil {
		return m.UserTokenInfo
	}
	return nil
}

func (m *IMGetDeviceTokenRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRoleSet struct {
	// cmd id:	0x0707
	Master           *uint32 `protobuf:"varint,1,req,name=master" json:"master,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMRoleSet) Reset()                    { *m = IMRoleSet{} }
func (m *IMRoleSet) String() string            { return proto.CompactTextString(m) }
func (*IMRoleSet) ProtoMessage()               {}
func (*IMRoleSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMRoleSet) GetMaster() uint32 {
	if m != nil && m.Master != nil {
		return *m.Master
	}
	return 0
}

type IMOnlineUserInfo struct {
	// cmd id:	0x0708
	UserStatList     []*IM_BaseDefine.ServerUserStat `protobuf:"bytes,1,rep,name=user_stat_list" json:"user_stat_list,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *IMOnlineUserInfo) Reset()                    { *m = IMOnlineUserInfo{} }
func (m *IMOnlineUserInfo) String() string            { return proto.CompactTextString(m) }
func (*IMOnlineUserInfo) ProtoMessage()               {}
func (*IMOnlineUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMOnlineUserInfo) GetUserStatList() []*IM_BaseDefine.ServerUserStat {
	if m != nil {
		return m.UserStatList
	}
	return nil
}

type IMMsgServInfo struct {
	// cmd id:	0x0709
	Ip1              *string `protobuf:"bytes,1,req,name=ip1" json:"ip1,omitempty"`
	Ip2              *string `protobuf:"bytes,2,req,name=ip2" json:"ip2,omitempty"`
	Port             *uint32 `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	MaxConnCnt       *uint32 `protobuf:"varint,4,req,name=max_conn_cnt" json:"max_conn_cnt,omitempty"`
	CurConnCnt       *uint32 `protobuf:"varint,5,req,name=cur_conn_cnt" json:"cur_conn_cnt,omitempty"`
	HostName         *string `protobuf:"bytes,6,req,name=host_name" json:"host_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMMsgServInfo) Reset()                    { *m = IMMsgServInfo{} }
func (m *IMMsgServInfo) String() string            { return proto.CompactTextString(m) }
func (*IMMsgServInfo) ProtoMessage()               {}
func (*IMMsgServInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMMsgServInfo) GetIp1() string {
	if m != nil && m.Ip1 != nil {
		return *m.Ip1
	}
	return ""
}

func (m *IMMsgServInfo) GetIp2() string {
	if m != nil && m.Ip2 != nil {
		return *m.Ip2
	}
	return ""
}

func (m *IMMsgServInfo) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *IMMsgServInfo) GetMaxConnCnt() uint32 {
	if m != nil && m.MaxConnCnt != nil {
		return *m.MaxConnCnt
	}
	return 0
}

func (m *IMMsgServInfo) GetCurConnCnt() uint32 {
	if m != nil && m.CurConnCnt != nil {
		return *m.CurConnCnt
	}
	return 0
}

func (m *IMMsgServInfo) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

type IMUserStatusUpdate struct {
	// cmd id:	0x070a
	UserStatus       *uint32                   `protobuf:"varint,1,req,name=user_status" json:"user_status,omitempty"`
	UserId           *uint32                   `protobuf:"varint,2,req,name=user_id" json:"user_id,omitempty"`
	ClientType       *IM_BaseDefine.ClientType `protobuf:"varint,3,req,name=client_type,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMUserStatusUpdate) Reset()                    { *m = IMUserStatusUpdate{} }
func (m *IMUserStatusUpdate) String() string            { return proto.CompactTextString(m) }
func (*IMUserStatusUpdate) ProtoMessage()               {}
func (*IMUserStatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMUserStatusUpdate) GetUserStatus() uint32 {
	if m != nil && m.UserStatus != nil {
		return *m.UserStatus
	}
	return 0
}

func (m *IMUserStatusUpdate) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUserStatusUpdate) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

type IMUserCntUpdate struct {
	// cmd id:	0x070b
	UserAction       *uint32 `protobuf:"varint,1,req,name=user_action" json:"user_action,omitempty"`
	UserId           *uint32 `protobuf:"varint,2,req,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMUserCntUpdate) Reset()                    { *m = IMUserCntUpdate{} }
func (m *IMUserCntUpdate) String() string            { return proto.CompactTextString(m) }
func (*IMUserCntUpdate) ProtoMessage()               {}
func (*IMUserCntUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMUserCntUpdate) GetUserAction() uint32 {
	if m != nil && m.UserAction != nil {
		return *m.UserAction
	}
	return 0
}

func (m *IMUserCntUpdate) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type IMServerKickUser struct {
	// cmd id:	0x070d
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	ClientType       *IM_BaseDefine.ClientType `protobuf:"varint,2,req,name=client_type,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	Reason           *uint32                   `protobuf:"varint,3,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMServerKickUser) Reset()                    { *m = IMServerKickUser{} }
func (m *IMServerKickUser) String() string            { return proto.CompactTextString(m) }
func (*IMServerKickUser) ProtoMessage()               {}
func (*IMServerKickUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMServerKickUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMServerKickUser) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMServerKickUser) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type IMServerPCLoginStatusNotify struct {
	// cmd id:	0x070e
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	LoginStatus      *uint32 `protobuf:"varint,2,req,name=login_status" json:"login_status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMServerPCLoginStatusNotify) Reset()                    { *m = IMServerPCLoginStatusNotify{} }
func (m *IMServerPCLoginStatusNotify) String() string            { return proto.CompactTextString(m) }
func (*IMServerPCLoginStatusNotify) ProtoMessage()               {}
func (*IMServerPCLoginStatusNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMServerPCLoginStatusNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMServerPCLoginStatusNotify) GetLoginStatus() uint32 {
	if m != nil && m.LoginStatus != nil {
		return *m.LoginStatus
	}
	return 0
}

type IMPushToUserReq struct {
	// cmd id:	0x070f
	Flash            *string                        `protobuf:"bytes,1,req,name=flash" json:"flash,omitempty"`
	Data             *string                        `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	UserTokenList    []*IM_BaseDefine.UserTokenInfo `protobuf:"bytes,3,rep,name=user_token_list" json:"user_token_list,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *IMPushToUserReq) Reset()                    { *m = IMPushToUserReq{} }
func (m *IMPushToUserReq) String() string            { return proto.CompactTextString(m) }
func (*IMPushToUserReq) ProtoMessage()               {}
func (*IMPushToUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMPushToUserReq) GetFlash() string {
	if m != nil && m.Flash != nil {
		return *m.Flash
	}
	return ""
}

func (m *IMPushToUserReq) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *IMPushToUserReq) GetUserTokenList() []*IM_BaseDefine.UserTokenInfo {
	if m != nil {
		return m.UserTokenList
	}
	return nil
}

type IMPushToUserRsp struct {
	// cmd id:	0x0710
	PushResultList   []*IM_BaseDefine.PushResult `protobuf:"bytes,1,rep,name=push_result_list" json:"push_result_list,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMPushToUserRsp) Reset()                    { *m = IMPushToUserRsp{} }
func (m *IMPushToUserRsp) String() string            { return proto.CompactTextString(m) }
func (*IMPushToUserRsp) ProtoMessage()               {}
func (*IMPushToUserRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMPushToUserRsp) GetPushResultList() []*IM_BaseDefine.PushResult {
	if m != nil {
		return m.PushResultList
	}
	return nil
}

type IMGroupGetShieldReq struct {
	// cmd id:			0x0711
	GroupId          *uint32  `protobuf:"varint,1,req,name=group_id" json:"group_id,omitempty"`
	UserId           []uint32 `protobuf:"varint,2,rep,name=user_id" json:"user_id,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMGroupGetShieldReq) Reset()                    { *m = IMGroupGetShieldReq{} }
func (m *IMGroupGetShieldReq) String() string            { return proto.CompactTextString(m) }
func (*IMGroupGetShieldReq) ProtoMessage()               {}
func (*IMGroupGetShieldReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMGroupGetShieldReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupGetShieldReq) GetUserId() []uint32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *IMGroupGetShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGroupGetShieldRsp struct {
	// cmd id: 			0x0712
	GroupId          *uint32                       `protobuf:"varint,1,req,name=group_id" json:"group_id,omitempty"`
	ShieldStatusList []*IM_BaseDefine.ShieldStatus `protobuf:"bytes,2,rep,name=shield_status_list" json:"shield_status_list,omitempty"`
	AttachData       []byte                        `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *IMGroupGetShieldRsp) Reset()                    { *m = IMGroupGetShieldRsp{} }
func (m *IMGroupGetShieldRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGroupGetShieldRsp) ProtoMessage()               {}
func (*IMGroupGetShieldRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IMGroupGetShieldRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupGetShieldRsp) GetShieldStatusList() []*IM_BaseDefine.ShieldStatus {
	if m != nil {
		return m.ShieldStatusList
	}
	return nil
}

func (m *IMGroupGetShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMFileTransferReq struct {
	// cmd id:			0x0715
	FromUserId       *uint32                         `protobuf:"varint,1,req,name=from_user_id" json:"from_user_id,omitempty"`
	ToUserId         *uint32                         `protobuf:"varint,2,req,name=to_user_id" json:"to_user_id,omitempty"`
	FileName         *string                         `protobuf:"bytes,3,req,name=file_name" json:"file_name,omitempty"`
	FileSize         *uint32                         `protobuf:"varint,4,req,name=file_size" json:"file_size,omitempty"`
	TransMode        *IM_BaseDefine.TransferFileType `protobuf:"varint,5,req,name=trans_mode,enum=IM.BaseDefine.TransferFileType" json:"trans_mode,omitempty"`
	AttachData       []byte                          `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *IMFileTransferReq) Reset()                    { *m = IMFileTransferReq{} }
func (m *IMFileTransferReq) String() string            { return proto.CompactTextString(m) }
func (*IMFileTransferReq) ProtoMessage()               {}
func (*IMFileTransferReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IMFileTransferReq) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMFileTransferReq) GetToUserId() uint32 {
	if m != nil && m.ToUserId != nil {
		return *m.ToUserId
	}
	return 0
}

func (m *IMFileTransferReq) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *IMFileTransferReq) GetFileSize() uint32 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *IMFileTransferReq) GetTransMode() IM_BaseDefine.TransferFileType {
	if m != nil && m.TransMode != nil {
		return *m.TransMode
	}
	return IM_BaseDefine.TransferFileType_FILE_TYPE_ONLINE
}

func (m *IMFileTransferReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMFileTransferRsp struct {
	// cmd id:			0x0716
	ResultCode       *uint32                         `protobuf:"varint,1,req,name=result_code" json:"result_code,omitempty"`
	FromUserId       *uint32                         `protobuf:"varint,2,req,name=from_user_id" json:"from_user_id,omitempty"`
	ToUserId         *uint32                         `protobuf:"varint,3,req,name=to_user_id" json:"to_user_id,omitempty"`
	FileName         *string                         `protobuf:"bytes,4,opt,name=file_name" json:"file_name,omitempty"`
	FileSize         *uint32                         `protobuf:"varint,5,opt,name=file_size" json:"file_size,omitempty"`
	TaskId           *string                         `protobuf:"bytes,6,opt,name=task_id" json:"task_id,omitempty"`
	TransMode        *IM_BaseDefine.TransferFileType `protobuf:"varint,7,opt,name=trans_mode,enum=IM.BaseDefine.TransferFileType" json:"trans_mode,omitempty"`
	AttachData       []byte                          `protobuf:"bytes,20,opt,name=attach_data" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *IMFileTransferRsp) Reset()                    { *m = IMFileTransferRsp{} }
func (m *IMFileTransferRsp) String() string            { return proto.CompactTextString(m) }
func (*IMFileTransferRsp) ProtoMessage()               {}
func (*IMFileTransferRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *IMFileTransferRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMFileTransferRsp) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMFileTransferRsp) GetToUserId() uint32 {
	if m != nil && m.ToUserId != nil {
		return *m.ToUserId
	}
	return 0
}

func (m *IMFileTransferRsp) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *IMFileTransferRsp) GetFileSize() uint32 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *IMFileTransferRsp) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *IMFileTransferRsp) GetTransMode() IM_BaseDefine.TransferFileType {
	if m != nil && m.TransMode != nil {
		return *m.TransMode
	}
	return IM_BaseDefine.TransferFileType_FILE_TYPE_ONLINE
}

func (m *IMFileTransferRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMFileServerIPReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMFileServerIPReq) Reset()                    { *m = IMFileServerIPReq{} }
func (m *IMFileServerIPReq) String() string            { return proto.CompactTextString(m) }
func (*IMFileServerIPReq) ProtoMessage()               {}
func (*IMFileServerIPReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type IMFileServerIPRsp struct {
	// cmd id:			0x0718
	IpAddrList       []*IM_BaseDefine.IpAddr `protobuf:"bytes,1,rep,name=ip_addr_list" json:"ip_addr_list,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *IMFileServerIPRsp) Reset()                    { *m = IMFileServerIPRsp{} }
func (m *IMFileServerIPRsp) String() string            { return proto.CompactTextString(m) }
func (*IMFileServerIPRsp) ProtoMessage()               {}
func (*IMFileServerIPRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *IMFileServerIPRsp) GetIpAddrList() []*IM_BaseDefine.IpAddr {
	if m != nil {
		return m.IpAddrList
	}
	return nil
}

func init() {
	proto.RegisterType((*IMStopReceivePacket)(nil), "IM.Server.IMStopReceivePacket")
	proto.RegisterType((*IMValidateReq)(nil), "IM.Server.IMValidateReq")
	proto.RegisterType((*IMValidateRsp)(nil), "IM.Server.IMValidateRsp")
	proto.RegisterType((*IMGetDeviceTokenReq)(nil), "IM.Server.IMGetDeviceTokenReq")
	proto.RegisterType((*IMGetDeviceTokenRsp)(nil), "IM.Server.IMGetDeviceTokenRsp")
	proto.RegisterType((*IMRoleSet)(nil), "IM.Server.IMRoleSet")
	proto.RegisterType((*IMOnlineUserInfo)(nil), "IM.Server.IMOnlineUserInfo")
	proto.RegisterType((*IMMsgServInfo)(nil), "IM.Server.IMMsgServInfo")
	proto.RegisterType((*IMUserStatusUpdate)(nil), "IM.Server.IMUserStatusUpdate")
	proto.RegisterType((*IMUserCntUpdate)(nil), "IM.Server.IMUserCntUpdate")
	proto.RegisterType((*IMServerKickUser)(nil), "IM.Server.IMServerKickUser")
	proto.RegisterType((*IMServerPCLoginStatusNotify)(nil), "IM.Server.IMServerPCLoginStatusNotify")
	proto.RegisterType((*IMPushToUserReq)(nil), "IM.Server.IMPushToUserReq")
	proto.RegisterType((*IMPushToUserRsp)(nil), "IM.Server.IMPushToUserRsp")
	proto.RegisterType((*IMGroupGetShieldReq)(nil), "IM.Server.IMGroupGetShieldReq")
	proto.RegisterType((*IMGroupGetShieldRsp)(nil), "IM.Server.IMGroupGetShieldRsp")
	proto.RegisterType((*IMFileTransferReq)(nil), "IM.Server.IMFileTransferReq")
	proto.RegisterType((*IMFileTransferRsp)(nil), "IM.Server.IMFileTransferRsp")
	proto.RegisterType((*IMFileServerIPReq)(nil), "IM.Server.IMFileServerIPReq")
	proto.RegisterType((*IMFileServerIPRsp)(nil), "IM.Server.IMFileServerIPRsp")
}

func init() { proto.RegisterFile("IM.Server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xed, 0x6e, 0xe3, 0x44,
	0x14, 0x95, 0xe3, 0xb4, 0xbb, 0xb9, 0x49, 0xfa, 0xe1, 0x74, 0x85, 0xa1, 0x20, 0x22, 0x4b, 0x48,
	0x11, 0x48, 0x91, 0xe8, 0x6a, 0xb5, 0x3f, 0xf8, 0x03, 0xdb, 0x6a, 0x17, 0x0b, 0x0c, 0x55, 0xd2,
	0xe5, 0xaf, 0x35, 0xb2, 0xaf, 0x9b, 0xa1, 0xce, 0xcc, 0xec, 0xcc, 0x38, 0x50, 0x5e, 0x82, 0x27,
	0xe1, 0x69, 0x78, 0x21, 0x34, 0x33, 0x4e, 0xb6, 0x76, 0x5c, 0x55, 0xe2, 0x67, 0x6e, 0xe6, 0xde,
	0x73, 0xce, 0x3d, 0xe7, 0x1a, 0x8e, 0xe3, 0x64, 0xbe, 0x44, 0xb9, 0x41, 0x39, 0x17, 0x92, 0x6b,
	0x1e, 0x0c, 0x76, 0x85, 0xcf, 0x26, 0x71, 0x32, 0x7f, 0x43, 0x14, 0x5e, 0x61, 0x41, 0x19, 0xba,
	0xff, 0xa3, 0xaf, 0x60, 0x12, 0x27, 0x4b, 0xcd, 0xc5, 0x02, 0x33, 0xa4, 0x1b, 0xbc, 0x26, 0xd9,
	0x1d, 0xea, 0xe0, 0x08, 0x0e, 0x25, 0xaa, 0xaa, 0xd4, 0xa1, 0x37, 0xed, 0xcd, 0xc6, 0x51, 0x0c,
	0xe3, 0x38, 0xf9, 0x8d, 0x94, 0x34, 0x27, 0x1a, 0x17, 0xf8, 0x21, 0x38, 0x85, 0x41, 0xa5, 0x50,
	0xa6, 0x8c, 0xac, 0xd1, 0xbe, 0x19, 0x04, 0x27, 0xf0, 0x5c, 0x10, 0xa5, 0xfe, 0xe0, 0x32, 0x0f,
	0x7b, 0xb6, 0x32, 0x81, 0x21, 0xd1, 0x9a, 0x64, 0xab, 0x34, 0x27, 0x9a, 0x84, 0x67, 0x53, 0x6f,
	0x36, 0x8a, 0xfe, 0xf6, 0x1a, 0xb3, 0x94, 0xe8, 0x9a, 0x35, 0x81, 0xa1, 0xc3, 0x4f, 0x33, 0x9e,
	0xa3, 0x1d, 0x37, 0x0e, 0x5e, 0xc0, 0xb8, 0x2e, 0x2a, 0x2d, 0x29, 0xbb, 0x0d, 0xfd, 0xa9, 0x37,
	0x1b, 0x04, 0x5f, 0xd7, 0xed, 0x94, 0x15, 0x3c, 0xec, 0x4f, 0xbd, 0xd9, 0xf0, 0xe2, 0x93, 0x79,
	0x53, 0xeb, 0x7b, 0x85, 0x32, 0x66, 0x05, 0xef, 0x66, 0xf4, 0x9d, 0xd9, 0xc1, 0x3b, 0xd4, 0x57,
	0xb8, 0xa1, 0x19, 0xde, 0xf0, 0x3b, 0x64, 0x46, 0xe2, 0x31, 0x3c, 0x73, 0x73, 0xf3, 0xd0, 0x9b,
	0xfa, 0xb3, 0x71, 0x77, 0x33, 0xe9, 0x68, 0x56, 0x22, 0x78, 0x05, 0xc7, 0xb6, 0x59, 0x9b, 0x82,
	0xa3, 0x66, 0x86, 0x0c, 0x2f, 0x3e, 0xef, 0xa0, 0x66, 0xbb, 0x1e, 0xe7, 0x77, 0x0e, 0x83, 0x38,
	0x59, 0xf0, 0x12, 0x97, 0xce, 0x99, 0x35, 0x51, 0x1a, 0xe5, 0xce, 0x99, 0x93, 0x38, 0xf9, 0x95,
	0x95, 0x94, 0xe1, 0x4e, 0xe5, 0x2b, 0x38, 0xb2, 0xe0, 0x4a, 0x13, 0x9d, 0x96, 0x54, 0xe9, 0x1a,
	0xfb, 0x8b, 0x16, 0xb6, 0x0b, 0x86, 0x69, 0x5b, 0x6a, 0xa2, 0xa3, 0x8d, 0x31, 0x26, 0x51, 0xb7,
	0xa6, 0x6c, 0xe7, 0x0c, 0xc1, 0xa7, 0xe2, 0xdb, 0xda, 0x12, 0xfb, 0xe3, 0xa2, 0x76, 0x76, 0x04,
	0x7d, 0xc1, 0xa5, 0x0e, 0x7d, 0x6b, 0xcc, 0x19, 0x8c, 0xd6, 0xe4, 0xcf, 0x34, 0xe3, 0x8c, 0xa5,
	0x19, 0xd3, 0x61, 0x7f, 0x5b, 0xcd, 0x2a, 0xf9, 0xb1, 0x7a, 0x60, 0xab, 0xa7, 0x30, 0x58, 0x71,
	0xa5, 0x9d, 0xd9, 0x87, 0x66, 0x58, 0xf4, 0x3b, 0x04, 0x71, 0xb2, 0x65, 0x51, 0xa9, 0xf7, 0xc2,
	0x04, 0xc3, 0xac, 0x62, 0x27, 0xa2, 0x52, 0x4e, 0xed, 0x43, 0x4f, 0x5c, 0x26, 0xe6, 0x30, 0xcc,
	0x4a, 0x8a, 0x4c, 0xa7, 0xfa, 0x5e, 0xa0, 0xe5, 0x73, 0x74, 0xf1, 0x69, 0x4b, 0xe7, 0xa5, 0x7d,
	0x71, 0x73, 0x2f, 0x30, 0x7a, 0x6d, 0x4e, 0xc4, 0x60, 0x5d, 0x32, 0xdd, 0x02, 0x22, 0x99, 0xa6,
	0x9c, 0x3d, 0x02, 0x14, 0x65, 0x66, 0xcf, 0x6e, 0x61, 0x3f, 0xd1, 0xec, 0xce, 0x8c, 0x68, 0x26,
	0xa4, 0x83, 0x4d, 0xef, 0x09, 0x36, 0xee, 0xcc, 0x88, 0xe2, 0xcc, 0x2d, 0x32, 0xba, 0x82, 0xf3,
	0x2d, 0xc8, 0xf5, 0xe5, 0xcf, 0xfc, 0x96, 0x32, 0xb7, 0x92, 0x5f, 0xb8, 0xa6, 0xc5, 0xfd, 0x3e,
	0xde, 0x19, 0x8c, 0x4a, 0xf3, 0x6a, 0xbb, 0x24, 0x47, 0x15, 0x8d, 0xc6, 0xeb, 0x4a, 0xad, 0x6e,
	0xb8, 0xa1, 0x69, 0xb2, 0x3c, 0x86, 0x83, 0xa2, 0x24, 0x6a, 0x55, 0x7b, 0x39, 0x82, 0xbe, 0xcd,
	0x97, 0x33, 0xb3, 0x99, 0x55, 0x9b, 0x17, 0xff, 0xe9, 0xac, 0x46, 0x6f, 0x5b, 0x30, 0x4a, 0x04,
	0x2f, 0xe1, 0x44, 0x54, 0x6a, 0x95, 0xd6, 0x67, 0xfa, 0x20, 0x7a, 0xed, 0x25, 0x98, 0xbe, 0x85,
	0x7d, 0x15, 0x25, 0xf6, 0x82, 0x24, 0xaf, 0xc4, 0x3b, 0xd4, 0xcb, 0x15, 0xc5, 0x32, 0x37, 0x94,
	0x4f, 0xe0, 0xf9, 0xad, 0x29, 0x7e, 0x54, 0xdb, 0xf0, 0xe4, 0xd1, 0x83, 0xac, 0x3a, 0xc6, 0x29,
	0xd1, 0x31, 0xee, 0x35, 0x04, 0xca, 0xfe, 0x5d, 0x6f, 0xcf, 0xd1, 0xed, 0x59, 0xba, 0xe7, 0xed,
	0x4b, 0xb1, 0x0f, 0x9d, 0x19, 0xdd, 0xb0, 0xff, 0x78, 0x70, 0x1a, 0x27, 0x6f, 0x69, 0x89, 0x37,
	0x92, 0x30, 0x55, 0xb8, 0xbd, 0x9f, 0xc1, 0xa8, 0x90, 0x7c, 0x9d, 0x36, 0x6d, 0x0b, 0x00, 0x34,
	0x4f, 0x9b, 0x41, 0x3e, 0x85, 0x41, 0x41, 0x4b, 0x74, 0x77, 0xe1, 0x5b, 0x5f, 0xb6, 0x25, 0x45,
	0xff, 0xc2, 0xfa, 0xa6, 0x5e, 0x02, 0x68, 0x33, 0x3e, 0x5d, 0x9b, 0xcf, 0xe2, 0x81, 0xcd, 0xd7,
	0x97, 0x2d, 0xae, 0x5b, 0x7c, 0xcb, 0xc5, 0xa4, 0xac, 0x93, 0xef, 0xbf, 0xfb, 0x7c, 0x95, 0x68,
	0x7f, 0x77, 0x77, 0x29, 0x6b, 0x88, 0xe8, 0x75, 0x88, 0xf0, 0xf7, 0x45, 0xf4, 0xed, 0xd7, 0xb9,
	0x21, 0xe2, 0x60, 0xea, 0x39, 0x1f, 0x35, 0x51, 0x77, 0xa6, 0xed, 0xd0, 0xbe, 0x69, 0xaa, 0x7a,
	0x36, 0xf5, 0xfe, 0xb7, 0xaa, 0xc9, 0x56, 0x94, 0x3b, 0xa2, 0xf8, 0x7a, 0x81, 0x1f, 0xa2, 0xef,
	0xf7, 0x8a, 0x4a, 0x04, 0xdf, 0xc0, 0x88, 0x8a, 0x94, 0xe4, 0xb9, 0x7c, 0x18, 0xd3, 0x17, 0x2d,
	0xd4, 0x58, 0xfc, 0x90, 0xe7, 0xf2, 0x4d, 0xef, 0x47, 0xff, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x37, 0x7e, 0xa3, 0xca, 0x5b, 0x07, 0x00, 0x00,
}
